#!/usr/bin/env bash
# Usage: xcenv completions <command> [arg1 arg2...]

set -e
[ -n "$XCENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  xcenv-help --usage completions >&2
  exit 1
fi

# Provide xcenv completions
if [ "$COMMAND" = "--complete" ]; then
  exec xcenv-commands
fi

COMMAND_PATH="$(command -v "xcenv-$COMMAND" || command -v "xcenv-sh-$COMMAND")"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide xcenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi