#!/usr/bin/env bash
# Usage: xcenv version-file [<dir>]
# Summary: Detect the file that sets the current xcenv version

set -e
[ -n "$XCENV_DEBUG" ] && set -x

target_dir="$1"

find_local_version_file() {
  local root="$1"
  while ! [[ "$root" =~ ^//[^/]*$ ]]; do
    if [ -e "${root}/.xcode-version" ]; then
      echo "${root}/.xcode-version"
      return 0
    fi
    [ -n "$root" ] || break
    root="${root%/*}"
  done
  return 1
}

if [ -n "$target_dir" ]; then
  find_local_version_file "$target_dir"
else
  find_local_version_file "$PWD" || {
    [ "$XCENV_DIR" != "$PWD" ] && find_local_version_file "$PWD"
  } || {
	[ -e "${XCENV_ROOT}/.xcode-version" ] && echo "${XCENV_ROOT}/.xcode-version"
  } || echo "system"
fi