#!/usr/bin/env bash
# Summary: Initialize the shims

set -e
[ -n "$XCENV_DEBUG" ] && set -x

# Provide xcenv completions
if [ "$1" = "--complete" ]; then
  echo -
  echo bash
  echo fish
  echo ksh
  echo zsh
  exit
fi

print=""
for args in "$@"
do
  if [ "$args" = "-" ]; then
    print=1
    shift
  fi
done

shell="$1"
if [ -z "$shell" ]; then
  shell="$(ps -p "$PPID" -o 'args=' 2>/dev/null || true)"
  shell="${shell%% *}"
  shell="${shell##-}"
  shell="${shell:-$SHELL}"
  shell="${shell##*/}"
fi

root="${0%/*}/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    if [ -f "${HOME}/.bashrc" ] && [ ! -f "${HOME}/.bash_profile" ]; then
      # shellcheck disable=SC2088
      profile='~/.bashrc'
    elif [ -f "${HOME}/.bash_profile" ]; then
      # shellcheck disable=SC2088
      profile='~/.bash_profile'
    else
      # shellcheck disable=SC2088
	  profile='~/.profile'
    fi
    ;;
  zsh )
    # shellcheck disable=SC2088
    profile='~/.zshrc'
    ;;
  ksh )
    # shellcheck disable=SC2088
    profile='~/.profile'
    ;;
  fish )
    # shellcheck disable=SC2088
    profile='~/.config/fish/config.fish'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load xcenv automatically by appending"
    echo "# the following to ${profile}:"
    echo
    case "$shell" in
    fish )
      echo 'status --is-interactive; and . (xcenv init -|psub)'
      ;;
    * )
      echo "eval \"\$(xcenv init -)\""
      ;;
    esac
    echo
  } >&2

  exit 1
fi

mkdir -p "${XCENV_ROOT}/shims"

case "$shell" in
fish )
  echo "setenv PATH '${XCENV_ROOT}/shims' \$PATH"
  echo "setenv XCENV_SHELL $shell"
;;
* )
  echo "export PATH=\"${XCENV_ROOT}/shims:\${PATH}\""
  echo "export XCENV_SHELL=$shell"
;;
esac

completion="${root}/completions/xcenv.${shell}"
if [ -r "$completion" ]; then
  case "$shell" in
  fish ) echo ". '$completion'" ;;
  *    ) echo "source '$completion'" ;;
  esac
fi

echo 'command xcenv rehash 2>/dev/null'

commands=($(xcenv-commands --sh))
case "$shell" in
fish )
  cat <<EOS
function xcenv
  set command \$argv[1]
  set -e argv[1]
  switch "\$command"
  case ${commands[*]}
    . (xcenv "sh-\$command" \$argv|psub)
  case '*'
    command xcenv "\$command" \$argv
  end
end
EOS
  ;;
ksh )
  cat <<EOS
function xcenv {
  typeset command
EOS
  ;;
* )
  cat <<EOS
xcenv() {
  local command
EOS
  ;;
esac

if [ "$shell" != "fish" ]; then
IFS="|"
cat <<EOS
  command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi
  case "\$command" in
  ${commands[*]})
    eval "\$(xcenv "sh-\$command" "\$@")";;
  *)
    command xcenv "\$command" "\$@";;
  esac
}
EOS
fi