#!/usr/bin/env bash
# Summary: Open the desired Xcode UI
#
# Usage: xcenv open [project or workspace]

[ -n "$XCENV_DEBUG" ] && set -x

PROJECT=$1

if [ -z "$PROJECT" ]; then
  PROJECT=$(find ./*.xcworkspace 2>/dev/null)
fi

if [ "$PROJECT" = "" ]; then
  PROJECT=$(find ./*.xcodeproj 2>/dev/null)
fi

open -a "$(xcenv-version-name)" "$PROJECT"
