#!/usr/bin/env bash

set -e
unset CDPATH

if [ "$1" == "--debug" ]; then
  export XCENV_DEBUG=1
  shift
fi

if [ -n "$XCENV_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

abort() {
  { if [ "$#" -eq 0 ]; then cat -
    else echo "xcenv: $*"
    fi
  } >&2
  exit 1
}

READLINK=$(type -p greadlink readlink | head -1)
[ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$PWD"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${XCENV_ROOT}" ]; then
  XCENV_ROOT="${HOME}/.xcenv"
else
  XCENV_ROOT="${XCENV_ROOT%/}"
fi
export XCENV_ROOT

if [ -z "${XCENV_DIR}" ]; then
  XCENV_DIR="$PWD"
else
  cd "XCENV_DIR" 2>/dev/null || abort "cannot change working directory to \`$XCENV_DIR'"
  XCENV_DIR="$PWD"
  cd "$OLDPWD"
fi
export XCENV_DIR

bin_path="$(abs_dirname "$0")"
export PATH="${bin_path}:${PATH}"

command="$1"
case "$command" in
"" )
  { xcenv---version
    xcenv-help
  } | abort
  ;;
-v | --version )
  exec xcenv---version
  ;;
-h | --help )
  exec xcenv-help
  ;;
* )
  command_path="$(command -v "xcenv-$command" || true)"
  [ -n "$command_path" ] || abort "no such command \`$command'"

  shift 1
  if [ "$1" = --help ]; then
    exec xcenv-help "$command"
  else
    exec "$command_path" "$@"
  fi
  ;;
esac