#!/usr/bin/env bash
#
# Summary: Set or show the local application-specific Xcode version
#
# Usage: xcenv local <version>
#        xcenv --unset

set -e
[ -n "$XCENV_DEBUG" ] && set -x

# Provide xcenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec xcenv-versions
  exit
fi

XCENV_VERSION="$1"

if [ "$XCENV_VERSION" = "--unset" ]; then
  rm -f .xcode-version
elif [ -n "$XCENV_VERSION" ]; then
  xcenv-version-file-write .xcode-version "$XCENV_VERSION"
else
  if version_file="$(xcenv-version-file "$PWD")"; then
    xcenv-version-file-read "$version_file"
  else
    echo "xcenv: no local version configured for this directory" >&2
    exit 1
  fi
fi