#!/usr/bin/env bash
# Summary: Rehashes the shims

set -e
[ -n "$XCENV_DEBUG" ] && set -x

XCENV_SHIM_LIST="BuildStrings CpMac DeRez GetFileInfo MergePef MvMac ResMerger Rez RezDet RezWack SetFile SplitForks UnRezWack agvtool ar as asa atos bison c++ c89 c99 cc clang clang++ cmpdylib codesign_allocate cpp ctags ctf_insert desdp dsymutil dwarfdump filtercalltree flex flex++ g++ gatherheaderdoc gcc gcov genstrings git git-cvsserver git-receive-pack git-shell git-upload-archive git-upload-pack gm4 gnumake gperf hdxml2manxml headerdoc2html heap ibtool ictool indent install_name_tool instruments iprofiler ld leaks lex libtool lipo lldb llvm-g++ llvm-gcc lorder m4 make malloc_history man manpath mig mkdep nasm ndisasm nm nmedit opendiff otool pagestuff ranlib rebase redo_prebinding resolveLinks rpcgen sample sdef sdp segedit size stringdups strings strip svn svnadmin svndumpfilter svnlook svnserve svnsync svnversion swift swiftc symbols unifdef unifdefall vmmap xcodebuild xcrun xed xml2man yacc"

XCENV_DO_NOT_SHIM_LIST=" $XCENV_DO_NOT_SHIM_LIST xcode-select "

READLINK=$(type -p greadlink readlink | head -1)
[ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$PWD"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

bin_path="$(abs_dirname "$0")"
SHIM_PATH="${XCENV_ROOT}/shims"

if [ -z "$USR_BIN" ]; then
  USR_BIN="/usr/bin"
fi

if [ ! -d "$USR_BIN" ]; then
  echo "$USR_BIN does not exist"
  exit 1
fi

for FILE_TO_SHIM in $XCENV_SHIM_LIST
do
  	[[ ! $XCENV_DO_NOT_SHIM_LIST =~ \ $FILE_TO_SHIM\  ]] && \
      [ -f "$USR_BIN/${FILE_TO_SHIM}" ] && \
      [ ! -f "${SHIM_PATH}/${FILE_TO_SHIM}" ] && \
      ln -s "${bin_path}/.shim" "${SHIM_PATH}/${FILE_TO_SHIM}"
done

for FILE_NOT_TO_SHIM in $XCENV_DO_NOT_SHIM_LIST
do
  if [ -f "${SHIM_PATH}/${FILE_NOT_TO_SHIM}" ]; then
    rm "${SHIM_PATH}/${FILE_NOT_TO_SHIM}"
  fi
done
