#!/usr/bin/env bash
# Summary: Rehashes the shims

set -e
[ -n "$XCENV_DEBUG" ] && set -x

DO_NOT_SHIM_LIST=("xcode-select")

READLINK=$(type -p greadlink readlink | head -1)
[ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$PWD"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

bin_path="$(abs_dirname "$0")"
SHIM_PATH="${XCENV_ROOT}/shims"

if [ -z "$USR_BIN" ]; then
  USR_BIN="/usr/bin"
fi

if [ ! -d "$USR_BIN" ]; then
  echo "$USR_BIN does not exist"
  exit 1
fi

FILES_NOT_SHIMMED=`diff -qr "${XCENV_ROOT}/shims" "$USR_BIN" 2> /dev/null | grep "^Only in $USR_BIN:" | cut -d: -f2-`

if [ -n "$FILES_NOT_SHIMMED" ]; then
  for FILE_TO_SHIM in $(cd "$USR_BIN"; LC_ALL=C grep -l "libxcselect.dylib" $FILES_NOT_SHIMMED 2>/dev/null)
  do
  	[[ ! $DO_NOT_SHIM_LIST =~ $FILE_TO_SHIM ]] && \
      ln -s "${bin_path}/.shim" "${SHIM_PATH}/$(basename $FILE_TO_SHIM)"
  done
fi

for FILE_NOT_TO_SHIM in $DO_NOT_SHIM_LIST
do
  if [ -f "${SHIM_PATH}/${FILE_NOT_TO_SHIM}" ]; then
    rm "${SHIM_PATH}/${FILE_NOT_TO_SHIM}"
  fi
done