#!/usr/bin/env bash
# Summary: Displays all versions of Xcode installed

set -e
[ -n "$XCENV_DEBUG" ] && set -x

IFS=$'\n'

for XCODE in $(xcenv-xcodes); do
	xcenv-xcode-version "$XCODE"
done

unset IFS