#!/bin/sh
# Summary: Rehashes the shims

set -e
[ -n "$XCENV_DEBUG" ] && set -x

READLINK=$(type -p greadlink readlink | head -1)
[ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$PWD"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

bin_path="$(abs_dirname "$0")"
FILES_NOT_SHIMMED=$(diff -qr "${XCENV_ROOT}/shims/" /usr/bin | grep '^Only in /usr/bin:' | cut -d: -f2-)
for FILE_TO_SHIM in $(cd /usr/bin; LC_ALL=C grep -l "libxcselect.dylib" $FILES_NOT_SHIMMED 2>/dev/null)
do
	ln -s "${bin_path}/.shim" "${XCENV_ROOT}/shims/$(basename $FILE_TO_SHIM)"
done