#!/usr/bin/env bash
# Summary: Displays all shims

set -e
[ -n "$XCENV_DEBUG" ] && set -x

if [ "$(ls -A "${XCENV_ROOT}/shims")" ]; then
  for SHIM in ${XCENV_ROOT}/shims/*;
  do
	  echo "$SHIM";
  done
else
  echo "No shims installed"
fi